meta-phosphor: npcm8xx.bbclass: stop full image build when sign binary failed
When sign key file is not found or openssl command failed,
we should stop full image build and output related message.

Tested: build pass when sign key is found,
        build fail when sign key is not found and output below message:
        ERROR: obmc-phosphor-image-1.0-r0 do_sign_binary: Sign binary failed.

Signed-off-by: Tim Lee <timlee660101@gmail.com>
(cherry picked from commit d930092c5009c924656f0775cc1ff951516b113e)
Signed-off-by: Joseph Liu <kwliu@nuvoton.com>